sensors:


  logical_camera_0: # over bin
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_1: # over bin
    type: logical_camera
    pose:
      xyz: [5, -1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_2: # over bin
    type: logical_camera
    pose:
      xyz: [3.082385, 1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_3: # over bin
    type: logical_camera
    pose:
      xyz: [3.082385, -1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_4: # over shelf
    type: logical_camera
    pose:
      xyz: [-1.25 - 6*2.04, 3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_5: # over shelf
    type: logical_camera
    pose:
      xyz: [-3.25 - 6*2.04, 3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_6: # over shelf
    type: logical_camera
    pose:
      xyz: [-1.25 - 6*2.04, -3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_7: # over shelf
    type: logical_camera
    pose:
      xyz: [-3.25 - 6*2.04, -3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_8: # over shelf
    type: logical_camera
    pose:
      xyz: [-1.25 - 6*2.04, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_9: # over shelf
    type: logical_camera
    pose:
      xyz: [-3.25 - 6*2.04, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_10: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [-0.004795,-4, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_11: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [-0.004795, -2, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_12: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [-0.004795, 2, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_13: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [-0.004795, 4, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_14: # over agv 1
    type: logical_camera
    pose:
      xyz: [0, 7, 1.5]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_15: # over agv 2
    type: logical_camera
    pose:
      xyz: [0, -7, 1.5]
      rpy: [0, 'pi/2', 'pi/2']

  breakbeam_0:
    type: break_beam
    pose:
      xyz: [-0.004795, 4.492549, 0.879306]
      rpy: [0, 0, -1.557900]

  breakbeam_1:
    type: break_beam
    pose:
      xyz: [-0.004795, -4.492549, 0.879306]
      rpy: [0, 0, 'pi/2']

